### ISSUE TITLE
Implement automatic testing

### ISSUE THREAD

**Issue by kurt-stolle** [kurt-stolle/node-gamequery#9]
Implement an automatic testing service into the package, such as Travis or Codeship.

**Comment by rbreslow** [comment]
I would use Travis because they have the best integration with GitHub. 

What would we test against?

I'm thinking about serializing packets from each game and parsing them in the tests without actually querying any servers.

**Comment by kurt-stolle** [comment]
First of all, we've got to make sure that the code sctually does not contain any errors.

Then, a test script could test the output of some modules and make sure that it doesn't contain any wrong information.

**Comment by kurt-stolle** [comment]
Added a quick TravisCI test to make sure that nothing is severely broken
